version: '3.1'
services:
  node:
    build: .
    volumes:
    - "./backend:/app"
    ports:
    - "3001:3001"
    depends_on: 
      - postgres
  postgres:
    image: postgres
    environment: 
       POSTGRES_PASSWORD: 123456
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql